language: python

sudo: required

dist: focal

python:
  - 3.7
  - 3.8

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libdb5.3-dev
  - sudo apt-get -y install slurm-wlm
  - sudo apt-get -y install r-base-dev
  - sudo apt-get -y install samtools
  # Setup python dependencies
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install git+https://github.com/deltarod/PeakError.git
  - pip install codecov
  - sudo mkdir /var/spool/slurm-llnl/
  - sudo chown slurm /var/spool/slurm-llnl/
  - sudo mkdir /var/spool/slurmd/
  - sudo chown slurm /var/spool/slurmd/
  - cd jbrowse
  - ./setup.sh
  - cd ..

script:
  # Setup slurm.conf for testing
  - sudo cp slurm.conf /etc/slurm-llnl
  - sudo service munge start
  - sudo systemctl restart slurmctld
  - sudo systemctl restart slurmd
  - sinfo
  # Test
  - pytest tests/

after_success:
  - codecov

after_failure:
  - sudo journalctl -u slurmctld
  - sudo journalctl -u slurmd
  - sudo systemctl -l status slurmctld.service
  - sudo systemctl -l status slurmd.service
  - cat runlog.txt
  - cat data/PeakLearner-2.txt
  - cat data/PeakLearner-3.txt
  - cat data/PeakLearner-4.txt




