language: python
python:
  - "2.7"

before_install:
  - sudo mkdir /etc/slurm-llnl
  - sudo cp slurm.conf /etc/slurm-llnl
#  - cp batchtools.conf.R tests/testthat
#  - sudo /etc/init.d/slurmctld restart
#  - sudo /etc/init.d/slurmd restart
  - sudo apt-get install -y slurm-llnl
  - sudo apt-get install -y berkeley-db
  - sudo apt-get install -y bsddb3
  - sudo apt-get install -y http.server
#  - sudo /usr/sbin/create-munge-key
  - sudo service munge start
  - cd jbrowse

script:
    ./ourServer.py
    python testing.py

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # do we need this?

branches:
    only:
        test-branch

notifications:
  slack: capstoneteam2019-2020:99sHd15zMUNsTJEWiIUvlrF3
